dataset: "wikitext2"
model:
  hidden_size: 256
  n_heads: 4
  cond_dim: 64
  dropout: 0.1
  n_blocks: 4
interpolant:
  type: "any-order"
  max_length: 512
  mask_schedule:
    type: "geometric"
    min: 5
    max: 0.01
training:
  batch_size: 32
  learning_rate: 0.0001
  devices: 1
  num_epochs: 5
  checkpoint_dir: "checkpoints/wikitext2"
  save_top_k: 1
  save_every_n_epochs: 1
  loss_fn:
    unmask: "cross_entropy"
    insert: "expectation"
wandb:
  entity: "jaeyeon_kim-harvard-university"
  project: "interpretable-flow"
  name: "wikitext2-any-order"
  