trainer: "any-order-flow"
dataset: "openwebtext"
model:
  hidden_size: 768
  n_heads: 12
  cond_dim: 128
  dropout: 0.05
  n_blocks: 12
interpolant:
  type: "any-order"
  tokens: null # filled in automatically
  pad_token: null # filled in automatically
  mask_token: null # filled in automatically
  max_length: 1024
  insert_schedule:
    type: "geometric"
    min: 5
    max: 0.01
  unmask_schedule:
    type: "linear"
training:
  batch_size: 1024
  per_gpu_batch_size: 64 # Gradient accumulation happens automatically
  cpus: 4
  learning_rate: 3e-4
  nodes: 4
  devices: 4
  max_steps: 500000
  weight_decay: 0.03
  checkpoint_dir: "checkpoints/openwebtext/any_order"
  save_top_k: 1
  save_every_n_epochs: 1
  loss_fn:
    unmask: "elbo"
    insert: "expectation"
  warmup_steps: 2000
  ema_decay: 0.9999
  filter_max_length: false
  resume_path: /n/netscratch/albergo_lab/Lab/brianlck/interpretable-flow/outputs/2025-07-06/12-28-01/checkpoints/openwebtext/any_order/20250706-122804/last.ckpt
wandb:
  entity: "jaeyeon_kim-harvard-university"
  project: "interpretable-flow"
  name: "openwebtext-any-order"
