trainer: "any-order-flow"
dataset: "bracket"
model:
  hidden_size: 256
  n_heads: 4
  cond_dim: 64
  dropout: 0.1
  n_blocks: 4
interpolant:
  type: "any-order"
  max_length: 64
  tokens: 4
  mask_token: 0
  pad_token: 3
  insert_schedule:
    type: "geometric"
    min: 5
    max: 0.01
  unmask_schedule:
    type: "linear"
training:
  batch_size: 32
  learning_rate: 0.0001
  devices: 1
  nodes: 1
  weight_decay: 0.01
  max_steps: null
  num_epochs: 100
  checkpoint_dir: "/n/netscratch/albergo_lab/Lab/brianlck/interpretable-flow/checkpoints/bracket/any_order"
  save_top_k: 1
  save_every_n_epochs: 1
  loss_fn:
    unmask: "elbo"
    insert: "expectation"
  warmup_steps: 1000
  ema_decay: 0.9999
wandb:
  entity: "jaeyeon_kim-harvard-university"
  project: "interpretable-flow"
  name: "bracket-any-order"
